DEFAULT_INTRESTS = {
  "Hobbies": {
    "Indoor": {
      "3D Printing": 0,
      "Acrobatics": 0,
      "Acting": 0,
      "Amateur Radio": 0,
      "Animation": 0,
      "Aqua-scaping": 0,
      "Baking": 0,
      "Baton Twirling": 0,
      "Beatboxing": 0,
      "Board Games": 0,
      "Book Restoration": 0,
      "Cabaret": 0,
      "Calligraphy": 0,
      "Candle Making": 0,
      "Coffee Roasting": 0,
      "Coloring": 0,
      "Computer Programming": 0,
      "Cooking": 0,
      "Cosplaying": 0,
      "Couponing": 0,
      "Creative Writing": 0,
      "Crocheting": 0,
      "Cross-stitch": 0,
      "Crossword Puzzles": 0,
      "Cryptography": 0,
      "Dance": 0,
      "Digital Arts": 0,
      "DIY": 0,
      "Drama": 0,
      "Drawing": 0,
      "Electronics": 0,
      "Embroidery": 0,
      "Fantasy Sports": 0,
      "Fashion": 0,
      "Fishkeeping": 0,
      "Flower Arranging": 0,
      "Foreign Languages": 0,
      "Gaming": 0,
      "Genealogy": 0,
      "Glassblowing": 0,
      "Graphic Design": 0,
      "Gunsmithing": 0,
      "Herp Keeping": 0,
      "Homebrewing": 0,
      "Hydroponics": 0,
      "Ice Skating": 0,
      "Jewelry Making": 0,
      "Jigsaw Puzzles": 0,
      "Juggling": 0,
      "Knife Making": 0,
      "Knitting": 0,
      "Kombucha Brewing": 0,
      "Lace making": 0,
      "Lapidary": 0,
      "Leather Crafting": 0,
      "Lego Building": 0,
      "Listening to Music": 0,
      "Machining": 0,
      "Macrame": 0,
      "Magic": 0,
      "Metalworking": 0,
      "Model Building": 0,
      "Model Engineering": 0,
      "Needlepoint": 0,
      "Origami": 0,
      "Painting": 0,
      "Pet": 0,
      "Philately": 0,
      "Photography": 0,
      "Musical Instruments": 0,
      "Poi": 0,
      "Pottery": 0,
      "Puzzles": 0,
      "Quilling": 0,
      "Quilting": 0,
      "Reading": 0,
      "Scrapbooking": 0,
      "Sculpting": 0,
      "Sewing": 0,
      "Singing": 0,
      "Sketching": 0,
      "Soap-making": 0,
      "Stand-up Comedy": 0,
      "Table tennis": 0,
      "Taxidermy": 0,
      "Video Game Developing": 0,
      "Video gaming": 0,
      "Watching Movies": 0,
      "Watching Television": 0,
      "Whittling": 0,
      "Wood Carving": 0,
      "Woodworking": 0,
      "Worldbuilding": 0,
      "Writing": 0,
      "Yo-yoing": 0,
      "Yoga": 0
    },
    "Outdoor": {
      "Air Sports": 0,
      "Archery": 0,
      "Astronomy": 0,
      "BASE Jumping": 0,
      "Baseball": 0,
      "Basketball": 0,
      "Beekeeping": 0,
      "Bird Watching": 0,
      "Blacksmithing": 0,
      "BMX": 0,
      "Board Sports": 0,
      "Bodybuilding": 0,
      "Brazilian Jiu-jitsu": 0,
      "Camping": 0,
      "Canoeing": 0,
      "Canyoning": 0,
      "Dowsing": 0,
      "Driving": 0,
      "Fishing": 0,
      "Flag Football": 0,
      "Flying": 0,
      "Flying Disc": 0,
      "Foraging": 0,
      "Freestyle Football": 0,
      "Gardening": 0,
      "Geocaching": 0,
      "Ghost Hunting": 0,
      "Graffiti": 0,
      "Handball": 0,
      "High-power Rocketry": 0,
      "Hiking": 0,
      "Hooping": 0,
      "Horseback Riding": 0,
      "Hunting": 0,
      "Inline Skating": 0,
      "Jogging": 0,
      "Kayaking": 0,
      "Kite Flying": 0,
      "Kitesurfing": 0,
      "LARPing": 0,
      "Letterboxing": 0,
      "Longboarding": 0,
      "Martial Arts": 0,
      "Metal Detecting": 0,
      "Motor Sports": 0,
      "Mountain Biking": 0,
      "Mountaineering": 0,
      "Mushroom Hunting/Mycology": 0,
      "Netball": 0,
      "Nordic Skating": 0,
      "Orienteering": 0,
      "Paintball": 0,
      "Parkour": 0,
      "Photography": 0,
      "Polo": 0,
      "Powerlifting": 0,
      "Rafting": 0,
      "Rappelling": 0,
      "Road Biking": 0,
      "Rock Climbing": 0,
      "Roller Skating": 0,
      "Rugby": 0,
      "Running": 0,
      "Sailing": 0,
      "Sand art": 0,
      "Scouting": 0,
      "Scuba Diving": 0,
      "Sculling or Rowing": 0,
      "Shooting": 0,
      "Shopping": 0,
      "Skateboarding": 0,
      "Skiing": 0,
      "Skim-boarding": 0,
      "Skydiving": 0,
      "Slacklining": 0,
      "Snowboarding": 0,
      "Stone Skipping": 0,
      "Sun Bathing": 0,
      "Surfing": 0,
      "Swimming": 0,
      "Taekwondo": 0,
      "Tai chi": 0,
      "Topiary": 0,
      "Travel": 0,
      "Urban Exploration": 0,
      "Vacation": 0,
      "Vehicle Restoration": 0,
      "Walking": 0,
      "Water Sports": 0
    }
  },
  "Collection Hobbies": {
    "Indoors": {
      "Action Figure": 0,
      "Antiquing": 0,
      "Art Collecting": 0,
      "Book Collecting": 0,
      "Card Collecting": 0,
      "Coin Collecting": 0,
      "Comic Book Collecting": 0,
      "Deltiology (Postcard Collecting)": 0,
      "Die-cast Toy": 0,
      "Element Collecting": 0,
      "Movie and Movie Memorabilia Collecting": 0,
      "Phillumeny": 0,
      "Rail Transport Modelling": 0,
      "Record Collecting": 0,
      "Shoes": 0,
      "Stamp Collecting": 0,
      "Video Game Collecting": 0,
      "Vintage Cars": 0
    },
    "Outdoors": {
      "Antiquities": 0,
      "Auto Audiophilia": 0,
      "Flower Collecting and Pressing": 0,
      "Fossil Hunting": 0,
      "Insect Collecting": 0,
      "Magnet Fishing": 0,
      "Metal Detecting": 0,
      "Mineral Collecting": 0,
      "Rock Balancing": 0,
      "Sea Glass Collecting": 0,
      "Seashell Collecting": 0,
      "Stone Collecting": 0
    }
  },
  "Competitive Hobbies": {
    "Indoors": {
      "Animal Fancy": 0,
      "Badminton": 0,
      "Baton Twirling": 0,
      "Billiards": 0,
      "Bowling": 0,
      "Boxing": 0,
      "Bridge": 0,
      "Cheerleading": 0,
      "Chess": 0,
      "Color Guard": 0,
      "Curling": 0,
      "Dancing": 0,
      "Competitive eating": 0,
      "Darts": 0,
      "Debate": 0,
      "ESports": 0,
      "Fencing": 0,
      "Go": 0,
      "Gymnastics": 0,
      "Ice skating": 0,
      "Kabaddi": 0,
      "Laser Tag": 0,
      "Longboarding": 0,
      "Mahjong": 0,
      "Marbles": 0,
      "Martial Arts": 0,
      "Poker": 0,
      "Slot Car Racing": 0,
      "Speed Cubing": 0,
      "Sport Stacking": 0,
      "Table Football": 0,
      "Volleyball": 0,
      "Weightlifting": 0,
      "Wrestling": 0
    },
    "Outdoors": {
      "Airsoft": 0,
      "American Football": 0,
      "Archery": 0,
      "Association Football": 0,
      "Australian Rules Football": 0,
      "Auto Racing": 0,
      "Baseball": 0,
      "Beach Volleyball": 0,
      "Breakdancing": 0,
      "Climbing": 0,
      "Cricket": 0,
      "Cycling": 0,
      "Disc Golf": 0,
      "Dog Sport": 0,
      "Equestrianism": 0,
      "Exhibition Drill": 0,
      "Field Hockey": 0,
      "Figure Skating": 0,
      "Fishing": 0,
      "Footbag": 0,
      "Golfing": 0,
      "Handball": 0,
      "Horseback Riding": 0,
      "Ice Hockey": 0,
      "Judo": 0,
      "Jukskei": 0,
      "Kart Racing": 0,
      "Knife Throwing": 0,
      "Lacrosse": 0,
      "Longboarding": 0,
      "Marching Band": 0,
      "Model Aircraft": 0,
      "Racquetball": 0,
      "Radio-controlled Car Racing": 0,
      "Roller Derby": 0,
      "Rugby League Football": 0,
      "Sculling or Rowing": 0,
      "Shooting Sports": 0,
      "Skateboarding": 0,
      "Speed Skating": 0,
      "Squash": 0,
      "Surfing": 0,
      "Swimming": 0,
      "Table Tennis": 0,
      "Tennis": 0,
      "Tennis Polo": 0,
      "Tether Car": 0,
      "Tour Skating": 0,
      "Triathlon": 0,
      "Ultimate Frisbee": 0,
      "Volleyball": 0,
      "Water Polo": 0
    }
  },
  "Observation Hobbies": {
    "Indoors": {
      "Fishkeeping": 0,
      "Meditation": 0,
      "Learning": 0,
      "Microscopy": 0,
      "Reading": 0,
      "Shortwave Listening": 0,
      "Videophilia": 0
    },
    "Outdoors": {
      "Aircraft Spotting": 0,
      "Amateur Astronomy": 0,
      "Astrology": 0,
      "Birdwatching": 0,
      "Bus spotting": 0,
      "Geocaching": 0,
      "Gongoozling": 0,
      "Herping": 0,
      "Hiking or Backpacking": 0,
      "Meteorology": 0,
      "Photography": 0,
      "Satellite Watching": 0,
      "Trainspotting": 0,
      "Traveling": 0,
      "Whale Watching": 0,
    }
  }
}
